# Your Website Title
title: 冰雪游戏工作室

# Your Website URL
url: 'https://bingxuegame.github.io/'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: BingXueGame
tagline: 
pic: profile.png # profile.png can be found at /assets/images/profile.png
description: 做个好游戏！！！
description_tiny: 联系邮箱:bx398864317@gmail.com
email: bx398864317@gmail.com
website: https://bingxuegame.github.io/
linkedin: 
github: BingXueGame
twitter: 

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm